apiVersion: apps/v1
kind: Deployment
metadata:
  name: new-python
spec:
  replicas: 3
  selector:
    matchLabels:
      app: todos
  template:
    metadata:
      labels:
        app: todos
    spec:
      containers:
      - name: todos-container
        image: yamini0727/django-app
        ports:
        - containerPort: 8000
