apiVersion: apps/v1
kind: Deployment
metadata:
  name: todos
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todos
  template:
    metadata:
      labels:
        app: todos
    spec:
      containers:
      - name: todos
        image: yamini0727/python-new-app
        ports:
        - containerPort: 8000
