apiVersion: v1
kind: Service
metadata:
  name: todos
spec:
  selector:
    app: todos
  ports:
    - name: http
      port: 8000
      targetPort: 8000
  type: LoadBalancer
  externalIPs:
  -  52.66.207.242
